### PR TITLE
Add a first pass of the `Editor Differences` wiki page

### PR DESCRIPTION
**Pull request by Digitalfear117**
Still lots and lots and lots to document, this is only a stub and mostly goes over .osu v1 to v5 in depth.

### CODE REVIEW

**Review by Lekuruu — CHANGES_REQUESTED** [review]
I would recommend to add all images to a local `img` subfolder, just to be consistent here.

**Comment by Digitalfear117** [comment]
Okay, will add the images to a subfolder, it was just inconvenient to do so while writing this since I didn’t write this on github, I wrote it on a markdown website. I can update it though. 

I didn’t realize I reference myself more then just at the top, this probably is too much article too little wiki lol

**Comment by Digitalfear117** [comment]
Is this more what you were thinking?

**Comment by Lekuruu** [comment]
Yup 👍

**Comment by Lekuruu** [comment]
This is still a work-in-progress, right?

**Comment by Digitalfear117** [comment]
yeah, but it's probably in a good enough state for people to see

**Comment by Lekuruu** [comment]
@Digitalfear117 would this be ready?

**Comment by Digitalfear117** [comment]
Hi sorry for the late response. This should be in an okay spot to go. There's a lot more things that could be added, but I'm a bit too busy with other projects.

**Review by Lekuruu — APPROVED** [review]

**Pull request merged**
