### PR TITLE
Update `Early Passengers`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Lekuruu — DISMISSED** [review]
yuh

**Comment by iSlodinxOsu** [comment]
> yuh

Could you rename the folder aswell?

**Comment by Lekuruu** [comment]
Why me, you made the pull request

**Comment by iSlodinxOsu** [comment]
> Why me, you made the pull request

Because idk how to do in on browser

**Comment by Lekuruu** [comment]
You have Google
https://github.blog/news-insights/product-news/moving-and-renaming-files-on-github/

**Comment by iSlodinxOsu** [comment]
> You have Google https://github.blog/news-insights/product-news/moving-and-renaming-files-on-github/

thanks.

**Review by Meruru-chan — APPROVED** [review]
w

**Comment by BlueChinchompa** [comment]
Looks good

**Review by BlueChinchompa — APPROVED** [review]
Looks good real edition

**Pull request merged**
